name: Run Jest Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: CourseAPP/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('CourseAPP/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: CourseAPP
        run: npm install

      - name: Show versions
        working-directory: CourseAPP
        run: |
          node -v
          npm -v
          npx jest --version

      - name: Run tests verbosely
        working-directory: CourseAPP
        run: npx jest --verbose --runInBand
